In [3]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression

In [5]:
df = pd.read_csv('train.csv.zip')
df

,id,bin_0,bin_1,bin_2,bin_3,bin_4,nom_0,nom_1,nom_2,nom_3,...,nom_9,ord_0,ord_1,ord_2,ord_3,ord_4,ord_5,day,month,target
0,0,0.0,0.0,0.0,F,N,Red,Trapezoid,Hamster,Russia,...,02e7c8990,3.0,Contributor,Hot,c,U,Pw,6.0,3.0,0
1,1,1.0,1.0,0.0,F,Y,Red,Star,Axolotl,NaN,...,f37df64af,3.0,Grandmaster,Warm,e,X,pE,7.0,7.0,0
2,2,0.0,1.0,0.0,F,N,Red,NaN,Hamster,Canada,...,NaN,3.0,NaN,Freezing,n,P,eN,5.0,9.0,0
3,3,NaN,0.0,0.0,F,N,Red,Circle,Hamster,Finland,...,f9d456e57,1.0,Novice,Lava Hot,a,C,NaN,3.0,3.0,0
4,4,0.0,NaN,0.0,T,N,Red,Triangle,Hamster,Costa Rica,...,c5361037c,3.0,Grandmaster,Cold,h,C,OZ,5.0,12.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,599995,0.0,1.0,0.0,T,N,Red,Polygon,Axolotl,India,...,015c63324,3.0,Novice,Freezing,a,R,GZ,5.0,NaN,0
599996,599996,1.0,0.0,0.0,T,Y,Blue,Polygon,Dog,Costa Rica,...,a02ae6a63,2.0,Novice,Boiling Hot,n,N,sf,NaN,3.0,0
599997,599997,0.0,0.0,0.0,F,Y,Red,Circle,Axolotl,Russia,...,40f9610c1,2.0,Contributor,Freezing,n,H,MV,7.0,5.0,0
599998,599998,1.0,1.0,0.0,F,Y,NaN,Polygon,Axolotl,NaN,...,c1a8374a0,1.0,Master,Warm,m,X,Ey,1.0,5.0,0
599999,599999,0.0,0.0,0.0,T,N,Blue,Triangle,Dog,Russia,...,e2aea7784,1.0,Contributor,Boiling Hot,b,O,uI,5.0,8.0,0

In [6]:
df_nona = df.dropna()
df_nona

,id,bin_0,bin_1,bin_2,bin_3,bin_4,nom_0,nom_1,nom_2,nom_3,...,nom_9,ord_0,ord_1,ord_2,ord_3,ord_4,ord_5,day,month,target
0,0,0.0,0.0,0.0,F,N,Red,Trapezoid,Hamster,Russia,...,02e7c8990,3.0,Contributor,Hot,c,U,Pw,6.0,3.0,0
6,6,0.0,0.0,0.0,F,N,Red,Triangle,Hamster,Costa Rica,...,4d3766412,1.0,Grandmaster,Cold,c,R,rg,5.0,6.0,0
7,7,0.0,0.0,1.0,T,N,Red,Triangle,Axolotl,Finland,...,a651dec43,3.0,Expert,Cold,b,Y,PS,1.0,1.0,0
10,10,0.0,0.0,1.0,T,Y,Blue,Triangle,Hamster,Finland,...,9bfe3ee22,1.0,Novice,Hot,b,O,hG,7.0,5.0,1
11,11,0.0,0.0,1.0,F,Y,Red,Square,Hamster,Costa Rica,...,6c73b62e4,1.0,Contributor,Hot,b,M,xF,2.0,8.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599990,599990,0.0,0.0,1.0,F,Y,Red,Polygon,Axolotl,India,...,411d37ac3,1.0,Novice,Freezing,i,E,DI,1.0,5.0,0
599991,599991,1.0,0.0,0.0,T,N,Blue,Triangle,Lion,India,...,2afbf5e88,3.0,Contributor,Warm,f,T,dp,1.0,8.0,0
599992,599992,1.0,0.0,0.0,T,N,Blue,Trapezoid,Hamster,Costa Rica,...,57934b610,2.0,Novice,Freezing,d,K,xF,7.0,12.0,0
599993,599993,0.0,1.0,0.0,F,N,Green,Triangle,Dog,Russia,...,a36361110,3.0,Contributor,Freezing,n,T,iv,7.0,12.0,0
599997,599997,0.0,0.0,0.0,F,Y,Red,Circle,Axolotl,Russia,...,40f9610c1,2.0,Contributor,Freezing,n,H,MV,7.0,5.0,0

In [9]:
df_nona.target.describe()

count    298042.000000
mean          0.187947
std           0.390670
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: target, dtype: float64

In [10]:
df.target.describe()

count    600000.000000
mean          0.187205
std           0.390076
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: target, dtype: float64